<#
.SYNOPSIS
Shared module for converting scoop list output to objects

.DESCRIPTION
Provides reusable function to convert scoop list output to objects and extract:
- App names
- Current versions
- Sources (buckets or auto-generated)
- Hold status (best-effort only - for authoritative detection use Get-HeldApps)

.PARAMETER ScoopShim
Path to Scoop shim executable

.EXAMPLE
Import-Module "$PSScriptRoot\ScoopList.psm1" -Force
$apps = ConvertFrom-ScoopList -ScoopShim $ScoopShim

.NOTES
The IsHeld field in the returned objects is best-effort only, parsed from console output.
For authoritative hold detection, use Get-HeldApps from UpdatableApps.psm1 which reads
from install.json files (metadata-based detection).
#>

function ConvertFrom-ScoopList {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory=$true)]
        [string]$ScoopShim
    )
    
    $apps = @()
    
    try {
        $projectRoot = Split-Path -Parent $PSScriptRoot
        Assert-ExternalCommandRunner -Caller 'ConvertFrom-ScoopList'

        $listCmd = Invoke-ExternalCommandLogged -ProjectRoot $projectRoot -FilePath $ScoopShim -ArgumentList @('list') -Stream:$false -NoHostOutput
        $listOutput = if ($listCmd.Output) { $listCmd.Output -split "\r?\n" } else { @() }
        $inTable = $false
        
        foreach ($line in $listOutput) {
            $trimmed = $line.Trim()
            
            if ($trimmed -match '^Name\s+Version') {
                $inTable = $true
                continue
            }
            if ($trimmed -match '^----') {
                continue
            }
            
            # Parse app lines
            if ($inTable -and $trimmed -and $trimmed -notmatch '^Installed apps:') {
                # Match app name, version, and source (source may be followed by "Held package" or other text)
                # Handle paths with spaces by intelligently splitting the line
                $appName = $null
                $version = $null
                $source = $null
                
                    # Split line by whitespace, but handle paths with spaces
                    $tokens = $trimmed -split '\s+'
                    if ($tokens.Count -ge 3) {
                        $appName = $tokens[0]
                        $version = $tokens[1]
                        $source = $tokens[2]
                        
                        # If source starts with drive letter, it's likely a path - collect tokens until we find path end markers
                        if ($source -match '^[a-zA-Z]:') {
                            $pathParts = @($source)
                            for ($i = 3; $i -lt $tokens.Count; $i++) {
                                $pathParts += $tokens[$i]
                                $combinedPath = ($pathParts -join ' ').Trim()
                                
                                # Stop conditions (in order of reliability):
                                # 1. Path ends with .json (most reliable - indicates complete manifest path)
                                # 2. Path contains \bucket\ (Scoop bucket structure)
                                # 3. Next token is a keyword like "Held", "pinned" (indicates path ended, keyword follows)
                                if ($combinedPath -match '\.json$' -or 
                                    $combinedPath -match '\\bucket\\' -or
                                    ($i + 1 -lt $tokens.Count -and $tokens[$i + 1] -match '^(Held|pinned|auto-generated)$')) {
                                    # Path is complete
                                    break
                                }
                            }
                            $source = ($pathParts -join ' ').Trim()
                        }
                    }
                
                if ($appName -and $version -and $source) {
                    
                    # Skip 'scoop' itself
                    if ($appName -eq 'scoop') { continue }
                    
                    # Extract bucket name from path or use as-is
                    $bucketName = $source
                    if ($source -match '\\([^\\]+)\\bucket\\') {
                        $bucketName = $Matches[1]
                    } elseif ($source -match '<auto-generated>') {
                        $bucketName = 'auto-generated'
                    }
                    
                    # Check if held (matches "Held" anywhere in the line - case insensitive)
                    # NOTE: This is best-effort only. For authoritative hold detection, use Get-HeldApps
                    # which reads from install.json files instead of parsing console output.
                    $isHeld = $trimmed -match '\bHeld\b'
                    
                    $apps += [pscustomobject]@{
                        Name = $appName
                        Version = $version
                        Source = $source
                        Bucket = $bucketName
                        IsHeld = $isHeld
                    }
                }
            }
        }
    } catch {
        # Return empty array on error
    }
    
    return $apps
}

Export-ModuleMember -Function @(
    'ConvertFrom-ScoopList'
)
