<#
.SYNOPSIS
Imports apps from canonical Scoop JSON export

.CMD
scoop import
#>

[CmdletBinding()]
param(
    [string]$File
)

$ErrorActionPreference = 'Stop'

# Path resolution
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Load bootstrap module
$BootstrapPath = Join-Path $ProjectRoot 'modules\ScriptBootstrap.psm1'
Import-Module $BootstrapPath -Force
$ctx = Initialize-ScriptEnvironment
$ScoopRoot = $ctx.ScoopRoot
$ScoopShim = $ctx.ScoopShim
$ScoopEnvModule = Join-Path $ProjectRoot 'modules\ScoopEnvironment.psm1'
Import-Module $ScoopEnvModule -Force

if (-not (Get-Command -Name Write-TextFileUtf8NoBom -ErrorAction SilentlyContinue)) {
    Write-Error "Write-TextFileUtf8NoBom helper is unavailable. Cannot continue with canonical import."
    exit 4
}

# Load shared modules
$FindLatestPath = Join-Path $ProjectRoot 'modules\LatestExportFile.psm1'
Import-Module $FindLatestPath -Force
$BeforeAfterPath = Join-Path $ProjectRoot 'modules\BeforeAfterState.psm1'
Import-Module $BeforeAfterPath -Force

# Load fresh installation check module
$TestFreshPath = Join-Path $ProjectRoot 'modules\FreshInstallation.psm1'
Import-Module $TestFreshPath -Force

# Load VirusTotal integration (required for import gating)
$vtSettings = $null
$VirusTotalInitPath = Join-Path $ProjectRoot 'modules\VirusTotalInit.psm1'
if (Test-Path -LiteralPath $VirusTotalInitPath) {
    Import-Module $VirusTotalInitPath -Force -ErrorAction SilentlyContinue
}
try {
    $vtSettings = Initialize-VirusTotalManagedFlow -ProjectRoot $ProjectRoot -OperationLabel 'import'
} catch {
    Write-Error $_.Exception.Message
    exit 4
}

# Load persist links module (optional)
$PersistLinksPath = Join-Path $ProjectRoot 'modules\PersistLinks.psm1'
if (Test-Path -LiteralPath $PersistLinksPath) {
    Import-Module $PersistLinksPath -Force
}

Write-SectionHeader -Title 'IMPORTING (CANONICAL FORMAT)'

# Pick default export file if none specified
if (-not $File) {
    $ConfigDir = Join-Path $ProjectRoot 'config\scoop'
    try {
        $File = Find-LatestExportFile -ConfigDir $ConfigDir -Pattern "export_scoop_*.json" -ErrorMessage "No export_scoop_*.json found in: $ConfigDir`n        Run script 79_Export-Scoop to create a canonical export first."
    } catch {
        exit 4
    }
}

$File = (Resolve-Path $File).Path

Write-Host "[*] Using Scoop shim: $ScoopShim"
Write-Host "[*] Importing from: $File"
Write-Host ""

# Check if Scoop is installed - required for importing apps (centralized check)
if (-not (Test-ScoopInstalled -ScoopRoot $ScoopRoot -ScoopShim $ScoopShim -ExitOnFailure)) {
    exit 4
}

# Check if installation is fresh (no apps installed except scoop)
$isFresh = Test-FreshInstallation -ScoopRoot $ScoopRoot -ScoopShim $ScoopShim
if (-not $isFresh) {
    # Apps are already installed - exit with code 4
    exit 4
}

Write-SubsectionHeader -Title 'Running Import'

$importFileToUse = $File
$tempImportFile = $null
$skipCount = 0
$shouldRunImport = $true

try {
    $json = Get-Content -Raw -Path $File | ConvertFrom-Json
} catch {
    Write-Error "Failed to parse canonical export JSON for VirusTotal checks: $($_.Exception.Message)"
    exit 4
}

if ($json.apps) {
    Write-Host "[*] Running VirusTotal checks for apps in import file..."
    Write-Host ""

    $approvedEntries = New-Object System.Collections.Generic.List[object]
    $allEntries = @($json.apps)

    foreach ($entry in $allEntries) {
        $appName = $null
        $appSpec = $null

        if ($entry -is [string]) {
            $rawEntry = $entry.Trim()
            if ([string]::IsNullOrWhiteSpace($rawEntry)) {
                continue
            }
            $appSpec = $rawEntry
            $namePart = ($rawEntry -split '@', 2)[0]
            if ($namePart -match '^[^/]+/(?<name>.+)$') {
                $appName = $Matches['name']
            } else {
                $appName = $namePart
            }
        } elseif ($entry.PSObject.Properties.Name -contains 'Name') {
            $appName = [string]$entry.Name
            if ([string]::IsNullOrWhiteSpace($appName)) {
                Write-Error "Import entry has empty app name and cannot be validated by VirusTotal."
                exit 4
            }

            $entryVersion = $null
            if ($entry.PSObject.Properties.Name -contains 'Version' -and $entry.Version) {
                $entryVersion = [string]$entry.Version
            }
            $entrySource = $null
            if ($entry.PSObject.Properties.Name -contains 'Source' -and $entry.Source) {
                $entrySource = ([string]$entry.Source).Trim()
            }
            $bucketSource = $null
            if ($entrySource -and $entrySource -ne '<auto-generated>' -and $entrySource -match '^[a-zA-Z0-9][a-zA-Z0-9._-]*$') {
                $bucketSource = $entrySource
            }

            if ($entryVersion) {
                if ($bucketSource) {
                    $appSpec = "$bucketSource/$appName@$entryVersion"
                } else {
                    $appSpec = "$appName@$entryVersion"
                }
            } else {
                if ($bucketSource) {
                    $appSpec = "$bucketSource/$appName"
                } else {
                    $appSpec = $appName
                }
            }
        } else {
            Write-Error "Unsupported app entry format in import file. Cannot run VirusTotal gate for this entry."
            exit 4
        }

        $vtGate = Invoke-VirusTotalGateForApp -AppName $appName -AppSpec $appSpec -ScoopShim $ScoopShim -Settings $vtSettings -Mode 'Install'
        if ($vtGate.Decision -eq 'Abort') {
            Write-Warning "Aborting canonical import due to VirusTotal decision."
            Write-Host ""
            exit 4
        }

        if ($vtGate.Decision -eq 'Skip') {
            $skipCount++
            Write-Host "[*] Skipping app from import: $appSpec"
            Write-Host ""
            continue
        }

        [void]$approvedEntries.Add($entry)
    }

    if ($skipCount -gt 0) {
        if ($approvedEntries.Count -eq 0) {
            Write-Host "[*] All apps were skipped by user decision. Nothing to import."
            Write-Host ""
            $shouldRunImport = $false
        } else {
            $tmpProcessDir = Join-Path $ProjectRoot '.tmp\process'
            if (-not (Test-Path -LiteralPath $tmpProcessDir)) {
                New-Item -ItemType Directory -Path $tmpProcessDir -Force | Out-Null
            }

            $tempImportFile = Join-Path $tmpProcessDir ("import_filtered_{0}.json" -f ([guid]::NewGuid().ToString('N')))
            $filtered = [ordered]@{}
            foreach ($prop in $json.PSObject.Properties) {
                if ($prop.Name -eq 'apps') {
                    $filtered['apps'] = @($approvedEntries.ToArray())
                } else {
                    $filtered[$prop.Name] = $prop.Value
                }
            }
            $filteredJson = $filtered | ConvertTo-Json -Depth 64
            Write-TextFileUtf8NoBom -Path $tempImportFile -Content $filteredJson
            $importFileToUse = $tempImportFile

            Write-Host "[*] Using filtered import file after skipping $skipCount app(s)."
            Write-Host ""
        }
    }
}

if ($shouldRunImport) {
    try {
        Write-Host "[*] Running: scoop import"
        $null = Invoke-ExternalCommandLogged -ProjectRoot $ProjectRoot -FilePath $ScoopShim -ArgumentList @('import', $importFileToUse) -Stream:$true
        Write-Host ""
    } finally {
        if ($tempImportFile -and (Test-Path -LiteralPath $tempImportFile)) {
            Remove-Item -LiteralPath $tempImportFile -Force -ErrorAction SilentlyContinue
        }
    }
}

if ($shouldRunImport) {
    Write-SectionHeader -Title '[OK] Import completed!'
} else {
    Write-SectionHeader -Title '[*] Import skipped (all apps were skipped by user decision)'
}

if (Get-Command -Name Invoke-PersistLinks -ErrorAction SilentlyContinue) {
    Invoke-PersistLinks -ProjectRoot $ProjectRoot -ScoopRoot $ScoopRoot
}

# Show final state
Show-BeforeAfterState -ScoopRoot $ScoopRoot -ScoopShim $ScoopShim -ShowAfter

exit 0
